import Head from 'next/head'
import AppNavBar from '../componentes/AppNavBar';
import AppCardBullets from '../componentes/AppCardBullets'

export default function Home() {
  let title = 'Milão APP';

  const bullets_today = [
    {type: 'event ', title:' Momento síncrono sobre componentes react'},
    {type: 'task   ', title:' Palavras chaves - bullet journal, github issues'},
  ];
  const bullets_tomorrow = [
    {type: 'task ', title: 'Priorizar as palavras-chaves'},
    {type: 'task ', title: 'Pesquisar imagens a partir das principais palavras-chaves'},
    {type: 'task ', title: 'Prototipar UI'}
  ];
  return (
    <div>
      <Head>
        	<title>{title}</title> <meta name = "description" 
		content = "Generated by create next app"/>
        	<link rel = "icon" href = "/favicon.ico"/>
        </Head>
      <main>
        <AppNavBar title={title} />
        <AppCardBullets date={"21/09/2021"} bullets={bullets_today}/>
        <AppCardBullets date={"28/09/2021"} bullets={bullets_tomorrow}/>
      </main>
    </div>
  )
}